/**
 * OpenAPI
 * tinkoff.ru/invest OpenAPI.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: n.v.melnikov@tinkoff.ru
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models

/**
 *
 * @param currency
 * @param balance
 * @param blocked
 */
data class CurrencyPosition(
    val currency: Currency,
    val balance: kotlin.Double,
    val blocked: kotlin.Double? = null
) {
}