/**
 * OpenAPI
 * tinkoff.ru/invest OpenAPI.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: n.v.melnikov@tinkoff.ru
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models


/**
 *
 * @param tradeId
 * @param date ISO8601
 * @param price
 * @param quantity
 */
data class OperationTrade(
    val tradeId: kotlin.String,
    /* ISO8601 */
    val date: java.time.LocalDateTime,
    val price: kotlin.Double,
    val quantity: kotlin.Int

) {
}