/**
 * OpenAPI
 * tinkoff.ru/invest OpenAPI.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: n.v.melnikov@tinkoff.ru
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models


/**
 *
 * Values: buy,buyCard,sell,brokerCommission,exchangeCommission,serviceCommission,marginCommission,otherCommission,payIn,payOut,tax,taxLucre,taxDividend,taxCoupon,taxBack,repayment,partRepayment,coupon,dividend,securityIn,securityOut
 */
enum class OperationTypeWithCommission(val value: kotlin.String) {
    buy("Buy"),// :/
    buyCard("BuyCard"),// :/
    sell("Sell"),// :/
    brokerCommission("BrokerCommission"),// :/
    exchangeCommission("ExchangeCommission"),// :/
    serviceCommission("ServiceCommission"),// :/
    marginCommission("MarginCommission"),// :/
    otherCommission("OtherCommission"),// :/
    payIn("PayIn"),// :/
    payOut("PayOut"),// :/
    tax("Tax"),// :/
    taxLucre("TaxLucre"),// :/
    taxDividend("TaxDividend"),// :/
    taxCoupon("TaxCoupon"),// :/
    taxBack("TaxBack"),// :/
    repayment("Repayment"),// :/
    partRepayment("PartRepayment"),// :/
    coupon("Coupon"),// :/
    dividend("Dividend"),// :/
    securityIn("SecurityIn"),// :/
    securityOut("SecurityOut");// :/
}