/**
* OpenAPI
* tinkoff.ru/invest OpenAPI.
*
* The version of the OpenAPI document: 1.0.0
* Contact: n.v.melnikov@tinkoff.ru
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models

import org.openapitools.client.models.CandleResolution

import com.squareup.moshi.Json
/**
 * 
 * @param figi 
 * @param interval 
 * @param o 
 * @param c 
 * @param h 
 * @param l 
 * @param v 
 * @param time ISO8601
 */

data class Candle (
    @Json(name = "figi")
    val figi: kotlin.String,
    @Json(name = "interval")
    val interval: CandleResolution,
    @Json(name = "o")
    val o: kotlin.Double,
    @Json(name = "c")
    val c: kotlin.Double,
    @Json(name = "h")
    val h: kotlin.Double,
    @Json(name = "l")
    val l: kotlin.Double,
    @Json(name = "v")
    val v: kotlin.Int,
    /* ISO8601 */
    @Json(name = "time")
    val time: java.time.OffsetDateTime
)

