/**
 * OpenAPI
 * tinkoff.ru/invest OpenAPI.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: n.v.melnikov@tinkoff.ru
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.client.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable


/**
 *
 * @param figi
 * @param interval
 * @param o
 * @param c
 * @param h
 * @param l
 * @param v
 * @param time ISO8601
 */

@Serializable
data class Candle(
    @SerialName("figi")
    val figi: String,
    @SerialName("interval")
    val interval: CandleResolution,
    @SerialName("o")
    val o: Double,
    @SerialName("c")
    val c: Double,
    @SerialName("h")
    val h: Double,
    @SerialName("l")
    val l: Double,
    @SerialName("v")
    val v: Int,
    /* ISO8601 */
    @SerialName("time")
    val time: java.time.OffsetDateTime
)

