/**
* OpenAPI
* tinkoff.ru/invest OpenAPI.
*
* The version of the OpenAPI document: 1.0.0
* Contact: n.v.melnikov@tinkoff.ru
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models

import org.openapitools.client.models.Candle
import org.openapitools.client.models.CandleResolution

import com.squareup.moshi.Json
/**
 * 
 * @param figi 
 * @param interval 
 * @param candles 
 */

data class Candles (
    @Json(name = "figi")
    val figi: kotlin.String,
    @Json(name = "interval")
    val interval: CandleResolution,
    @Json(name = "candles")
    val candles: kotlin.Array<Candle>
)

