/**
 * OpenAPI
 * tinkoff.ru/invest OpenAPI.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: n.v.melnikov@tinkoff.ru
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.client.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 *
 * @param currency
 * @param balance
 * @param blocked
 */

@Serializable
data class CurrencyPosition(
    @SerialName("currency")
    val currency: Currency,
    @SerialName("balance")
    val balance: Double,
    @SerialName("blocked")
    val blocked: Double? = null
)

