/**
* OpenAPI
* tinkoff.ru/invest OpenAPI.
*
* The version of the OpenAPI document: 1.0.0
* Contact: n.v.melnikov@tinkoff.ru
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models

import org.openapitools.client.models.Currency

import com.squareup.moshi.Json
/**
 * 
 * @param currency 
 * @param balance 
 * @param blocked 
 */

data class CurrencyPosition (
    @Json(name = "currency")
    val currency: Currency,
    @Json(name = "balance")
    val balance: kotlin.Double,
    @Json(name = "blocked")
    val blocked: kotlin.Double? = null
)

