/**
 * OpenAPI
 * tinkoff.ru/invest OpenAPI.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: n.v.melnikov@tinkoff.ru
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.client.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 *
 * @param lots
 * @param operation
 * @param price
 */

@Serializable
data class LimitOrderRequest(
    @SerialName("lots")
    val lots: Int,
    @SerialName("operation")
    val operation: OperationType,
    @SerialName("price")
    val price: Double
)

