/**
* OpenAPI
* tinkoff.ru/invest OpenAPI.
*
* The version of the OpenAPI document: 1.0.0
* Contact: n.v.melnikov@tinkoff.ru
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models

import org.openapitools.client.models.OperationType

import com.squareup.moshi.Json
/**
 * 
 * @param lots 
 * @param operation 
 * @param price 
 */

data class LimitOrderRequest (
    @Json(name = "lots")
    val lots: kotlin.Int,
    @Json(name = "operation")
    val operation: OperationType,
    @Json(name = "price")
    val price: kotlin.Double
)

