/**
* OpenAPI
* tinkoff.ru/invest OpenAPI.
*
* The version of the OpenAPI document: 1.0.0
* Contact: n.v.melnikov@tinkoff.ru
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models

import org.openapitools.client.models.MarketInstrument

import com.squareup.moshi.Json
/**
 * 
 * @param total 
 * @param instruments 
 */

data class MarketInstrumentList (
    @Json(name = "total")
    val total: java.math.BigDecimal,
    @Json(name = "instruments")
    val instruments: kotlin.Array<MarketInstrument>
)

