/**
 * OpenAPI
 * tinkoff.ru/invest OpenAPI.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: n.v.melnikov@tinkoff.ru
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.client.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 *
 * @param figi
 * @param ticker
 * @param lot
 * @param name
 * @param type
 * @param isin
 * @param minPriceIncrement Шаг цены
 * @param minQuantity Минимальное число инструментов для покупки должно быть не меньше, чем размер лота х количество лотов
 * @param currency
 */

@Serializable
data class MarketInstrument(
    @SerialName("figi")
    val figi: String,
    @SerialName("ticker")
    val ticker: String,
    @SerialName("lot")
    val lot: Int,
    @SerialName("name")
    val name: String,
    @SerialName("type")
    val type: InstrumentType,
    @SerialName("isin")
    val isin: String? = null,
    /* Шаг цены */
    @SerialName("minPriceIncrement")
    val minPriceIncrement: Double? = null,
    /* Минимальное число инструментов для покупки должно быть не меньше, чем размер лота х количество лотов */
    @SerialName("minQuantity")
    val minQuantity: Int? = null,
    @SerialName("currency")
    val currency: Currency? = null
)

