/**
 * OpenAPI
 * tinkoff.ru/invest OpenAPI.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: n.v.melnikov@tinkoff.ru
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.client.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 *
 * @param id
 * @param status
 * @param currency
 * @param payment
 * @param isMarginCall
 * @param date ISO8601
 * @param trades
 * @param commission
 * @param price
 * @param quantity Число инструментов в выставленной заявке
 * @param quantityExecuted Число инструментов, исполненных в заявке
 * @param figi
 * @param instrumentType
 * @param operationType
 */

@Serializable
data class Operation(
    @SerialName("id")
    val id: String,
    @SerialName("status")
    val status: OperationStatus,
    @SerialName("currency")
    val currency: Currency,
    @SerialName("payment")
    val payment: Double,
    @SerialName("isMarginCall")
    val isMarginCall: Boolean,
    /* ISO8601 */
    @SerialName("date")
    val date: java.time.OffsetDateTime,
    @SerialName("trades")
    val trades: List<OperationTrade>? = null,
    @SerialName("commission")
    val commission: MoneyAmount? = null,
    @SerialName("price")
    val price: Double? = null,
    /* Число инструментов в выставленной заявке */
    @SerialName("quantity")
    val quantity: Int? = null,
    /* Число инструментов, исполненных в заявке */
    @SerialName("quantityExecuted")
    val quantityExecuted: Int? = null,
    @SerialName("figi")
    val figi: String? = null,
    @SerialName("instrumentType")
    val instrumentType: InstrumentType? = null,
    @SerialName("operationType")
    val operationType: OperationTypeWithCommission? = null
)

