/**
* OpenAPI
* tinkoff.ru/invest OpenAPI.
*
* The version of the OpenAPI document: 1.0.0
* Contact: n.v.melnikov@tinkoff.ru
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models

import org.openapitools.client.models.Currency
import org.openapitools.client.models.InstrumentType
import org.openapitools.client.models.MoneyAmount
import org.openapitools.client.models.OperationStatus
import org.openapitools.client.models.OperationTrade
import org.openapitools.client.models.OperationTypeWithCommission

import com.squareup.moshi.Json
/**
 * 
 * @param id 
 * @param status 
 * @param currency 
 * @param payment 
 * @param isMarginCall 
 * @param date ISO8601
 * @param trades 
 * @param commission 
 * @param price 
 * @param quantity Число инструментов в выставленной заявке
 * @param quantityExecuted Число инструментов, исполненных в заявке
 * @param figi 
 * @param instrumentType 
 * @param operationType 
 */

data class Operation (
    @Json(name = "id")
    val id: kotlin.String,
    @Json(name = "status")
    val status: OperationStatus,
    @Json(name = "currency")
    val currency: Currency,
    @Json(name = "payment")
    val payment: kotlin.Double,
    @Json(name = "isMarginCall")
    val isMarginCall: kotlin.Boolean,
    /* ISO8601 */
    @Json(name = "date")
    val date: java.time.OffsetDateTime,
    @Json(name = "trades")
    val trades: kotlin.Array<OperationTrade>? = null,
    @Json(name = "commission")
    val commission: MoneyAmount? = null,
    @Json(name = "price")
    val price: kotlin.Double? = null,
    /* Число инструментов в выставленной заявке */
    @Json(name = "quantity")
    val quantity: kotlin.Int? = null,
    /* Число инструментов, исполненных в заявке */
    @Json(name = "quantityExecuted")
    val quantityExecuted: kotlin.Int? = null,
    @Json(name = "figi")
    val figi: kotlin.String? = null,
    @Json(name = "instrumentType")
    val instrumentType: InstrumentType? = null,
    @Json(name = "operationType")
    val operationType: OperationTypeWithCommission? = null
)

