/**
 * OpenAPI
 * tinkoff.ru/invest OpenAPI.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: n.v.melnikov@tinkoff.ru
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.client.models

import kotlinx.serialization.SerialName

/**
 * Статус заявки
 * Values: done,decline,progress
 */

enum class OperationStatus(val value: String) {


    @SerialName("Done")
    done("Done"),


    @SerialName("Decline")
    decline("Decline"),


    @SerialName("Progress")
    progress("Progress");


    /**
    This override toString avoids using the enum var name and uses the actual api value instead.
    In cases the var name and value are different, the client would send incorrect enums to the server.
     **/
    override fun toString(): String {
        return value
    }

}

