/**
* OpenAPI
* tinkoff.ru/invest OpenAPI.
*
* The version of the OpenAPI document: 1.0.0
* Contact: n.v.melnikov@tinkoff.ru
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models


import com.squareup.moshi.Json
/**
 * 
 * @param tradeId 
 * @param date ISO8601
 * @param price 
 * @param quantity 
 */

data class OperationTrade (
    @Json(name = "tradeId")
    val tradeId: kotlin.String,
    /* ISO8601 */
    @Json(name = "date")
    val date: java.time.OffsetDateTime,
    @Json(name = "price")
    val price: kotlin.Double,
    @Json(name = "quantity")
    val quantity: kotlin.Int
)

