/**
 * OpenAPI
 * tinkoff.ru/invest OpenAPI.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: n.v.melnikov@tinkoff.ru
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.client.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 *
 * @param tradeId
 * @param date ISO8601
 * @param price
 * @param quantity
 */

@Serializable
data class OperationTrade(
    @SerialName("tradeId")
    val tradeId: String,
    /* ISO8601 */
    @SerialName("date")
    val date: java.time.OffsetDateTime,
    @SerialName("price")
    val price: Double,
    @SerialName("quantity")
    val quantity: Int
)

