/**
* OpenAPI
* tinkoff.ru/invest OpenAPI.
*
* The version of the OpenAPI document: 1.0.0
* Contact: n.v.melnikov@tinkoff.ru
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models

import org.openapitools.client.models.OperationType
import org.openapitools.client.models.OrderStatus
import org.openapitools.client.models.OrderType

import com.squareup.moshi.Json
/**
 * 
 * @param orderId 
 * @param figi 
 * @param operation 
 * @param status 
 * @param requestedLots 
 * @param executedLots 
 * @param type 
 * @param price 
 */

data class Order (
    @Json(name = "orderId")
    val orderId: kotlin.String,
    @Json(name = "figi")
    val figi: kotlin.String,
    @Json(name = "operation")
    val operation: OperationType,
    @Json(name = "status")
    val status: OrderStatus,
    @Json(name = "requestedLots")
    val requestedLots: kotlin.Int,
    @Json(name = "executedLots")
    val executedLots: kotlin.Int,
    @Json(name = "type")
    val type: OrderType,
    @Json(name = "price")
    val price: kotlin.Double
)

