/**
 * OpenAPI
 * tinkoff.ru/invest OpenAPI.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: n.v.melnikov@tinkoff.ru
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.client.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 *
 * @param figi
 * @param depth
 * @param bids
 * @param asks
 * @param tradeStatus
 * @param minPriceIncrement Шаг цены
 * @param faceValue Номинал для облигаций
 * @param lastPrice
 * @param closePrice
 * @param limitUp Верхняя граница цены
 * @param limitDown Нижняя граница цены
 */

@Serializable
data class Orderbook(
    @SerialName("figi")
    val figi: String,
    @SerialName("depth")
    val depth: Int,
    @SerialName("bids")
    val bids: List<OrderResponse>,
    @SerialName("asks")
    val asks: List<OrderResponse>,
    @SerialName("tradeStatus")
    val tradeStatus: TradeStatus,
    /* Шаг цены */
    @SerialName("minPriceIncrement")
    val minPriceIncrement: Double,
    /* Номинал для облигаций */
    @SerialName("faceValue")
    val faceValue: Double? = null,
    @SerialName("lastPrice")
    val lastPrice: Double? = null,
    @SerialName("closePrice")
    val closePrice: Double? = null,
    /* Верхняя граница цены */
    @SerialName("limitUp")
    val limitUp: Double? = null,
    /* Нижняя граница цены */
    @SerialName("limitDown")
    val limitDown: Double? = null
)

