/**
* OpenAPI
* tinkoff.ru/invest OpenAPI.
*
* The version of the OpenAPI document: 1.0.0
* Contact: n.v.melnikov@tinkoff.ru
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models

import org.openapitools.client.models.OrderResponse
import org.openapitools.client.models.TradeStatus

import com.squareup.moshi.Json
/**
 * 
 * @param figi 
 * @param depth 
 * @param bids 
 * @param asks 
 * @param tradeStatus 
 * @param minPriceIncrement Шаг цены
 * @param faceValue Номинал для облигаций
 * @param lastPrice 
 * @param closePrice 
 * @param limitUp Верхняя граница цены
 * @param limitDown Нижняя граница цены
 */

data class Orderbook (
    @Json(name = "figi")
    val figi: kotlin.String,
    @Json(name = "depth")
    val depth: kotlin.Int,
    @Json(name = "bids")
    val bids: kotlin.Array<OrderResponse>,
    @Json(name = "asks")
    val asks: kotlin.Array<OrderResponse>,
    @Json(name = "tradeStatus")
    val tradeStatus: TradeStatus,
    /* Шаг цены */
    @Json(name = "minPriceIncrement")
    val minPriceIncrement: kotlin.Double,
    /* Номинал для облигаций */
    @Json(name = "faceValue")
    val faceValue: kotlin.Double? = null,
    @Json(name = "lastPrice")
    val lastPrice: kotlin.Double? = null,
    @Json(name = "closePrice")
    val closePrice: kotlin.Double? = null,
    /* Верхняя граница цены */
    @Json(name = "limitUp")
    val limitUp: kotlin.Double? = null,
    /* Нижняя граница цены */
    @Json(name = "limitDown")
    val limitDown: kotlin.Double? = null
)

