/**
 * OpenAPI
 * tinkoff.ru/invest OpenAPI.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: n.v.melnikov@tinkoff.ru
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.client.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 *
 * @param orderId
 * @param operation
 * @param status
 * @param requestedLots
 * @param executedLots
 * @param rejectReason
 * @param message Сообщение об ошибке
 * @param commission
 */

@Serializable
data class PlacedLimitOrder(
    @SerialName("orderId")
    val orderId: String,
    @SerialName("operation")
    val operation: OperationType,
    @SerialName("status")
    val status: OrderStatus,
    @SerialName("requestedLots")
    val requestedLots: Int,
    @SerialName("executedLots")
    val executedLots: Int,
    @SerialName("rejectReason")
    val rejectReason: String? = null,
    /* Сообщение об ошибке */
    @SerialName("message")
    val message: String? = null,
    @SerialName("commission")
    val commission: MoneyAmount? = null
)

