/**
 * OpenAPI
 * tinkoff.ru/invest OpenAPI.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: n.v.melnikov@tinkoff.ru
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.client.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 *
 * @param figi
 * @param instrumentType
 * @param balance
 * @param lots
 * @param name
 * @param ticker
 * @param isin
 * @param blocked
 * @param expectedYield
 * @param averagePositionPrice
 * @param averagePositionPriceNoNkd
 */

@Serializable
data class PortfolioPosition(
    @SerialName("figi")
    val figi: String,
    @SerialName("instrumentType")
    val instrumentType: InstrumentType,
    @SerialName("balance")
    val balance: Double,
    @SerialName("lots")
    val lots: Int,
    @SerialName("name")
    val name: String,
    @SerialName("ticker")
    val ticker: String? = null,
    @SerialName("isin")
    val isin: String? = null,
    @SerialName("blocked")
    val blocked: Double? = null,
    @SerialName("expectedYield")
    val expectedYield: MoneyAmount? = null,
    @SerialName("averagePositionPrice")
    val averagePositionPrice: MoneyAmount? = null,
    @SerialName("averagePositionPriceNoNkd")
    val averagePositionPriceNoNkd: MoneyAmount? = null
)

