/**
* OpenAPI
* tinkoff.ru/invest OpenAPI.
*
* The version of the OpenAPI document: 1.0.0
* Contact: n.v.melnikov@tinkoff.ru
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models

import org.openapitools.client.models.Currency
import org.openapitools.client.models.InstrumentType

import com.squareup.moshi.Json
/**
 * 
 * @param figi 
 * @param ticker 
 * @param lot 
 * @param name 
 * @param type 
 * @param isin 
 * @param minPriceIncrement Шаг цены
 * @param currency 
 */

data class SearchMarketInstrument (
    @Json(name = "figi")
    val figi: kotlin.String,
    @Json(name = "ticker")
    val ticker: kotlin.String,
    @Json(name = "lot")
    val lot: kotlin.Int,
    @Json(name = "name")
    val name: kotlin.String,
    @Json(name = "type")
    val type: InstrumentType,
    @Json(name = "isin")
    val isin: kotlin.String? = null,
    /* Шаг цены */
    @Json(name = "minPriceIncrement")
    val minPriceIncrement: kotlin.Double? = null,
    @Json(name = "currency")
    val currency: Currency? = null
)

