/**
 * OpenAPI
 * tinkoff.ru/invest OpenAPI.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: n.v.melnikov@tinkoff.ru
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.client.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 *
 * @param trackingId
 * @param status
 * @param payload
 */

@Serializable
data class UserAccountsResponse(
    @SerialName("trackingId")
    val trackingId: String,
    @SerialName("status")
    val status: String,
    @SerialName("payload")
    val payload: UserAccounts
)

