/**
 * OpenAPI
 * tinkoff.ru/invest OpenAPI.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: n.v.melnikov@tinkoff.ru
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models


/**
 * Интервал свечи и допустимый промежуток запроса: - 1min [1 minute, 1 day] - 2min [2 minutes, 1 day] - 3min [3 minutes, 1 day] - 5min [5 minutes, 1 day] - 10min [10 minutes, 1 day] - 15min [15 minutes, 1 day] - 30min [30 minutes, 1 day] - hour [1 hour, 7 days] - day [1 day, 1 year] - week [7 days, 2 years] - month [1 month, 10 years]
 * Values: 1min,2min,3min,5min,10min,15min,30min,hour,day,week,month
 */
enum class CandleResolution(val value: kotlin.String){
    min1("1min"),// :/
    min2("2min"),// :/
    min3("3min"),// :/
    min5("5min"),// :/
    min10("10min"),// :/
    min15("15min"),// :/
    min30("30min"),// :/
    hour("hour"),// :/
    day("day"),// :/
    week("week"),// :/
    month("month");// :/
}