/**
 * OpenAPI
 * tinkoff.ru/invest OpenAPI.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: n.v.melnikov@tinkoff.ru
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models

import io.swagger.client.models.Currency
import io.swagger.client.models.InstrumentType
import io.swagger.client.models.MoneyAmount
import io.swagger.client.models.OperationStatus
import io.swagger.client.models.OperationTrade
import io.swagger.client.models.OperationTypeWithCommission

/**
 * 
 * @param id 
 * @param status 
 * @param trades 
 * @param commission 
 * @param currency 
 * @param payment 
 * @param price 
 * @param quantity Число инструментов в выставленной заявке
 * @param quantityExecuted Число инструментов, исполненных в заявке
 * @param figi 
 * @param instrumentType 
 * @param isMarginCall 
 * @param date ISO8601
 * @param operationType 
 */
data class Operation (
    val id: kotlin.String,
    val status: OperationStatus,
    val currency: Currency,
    val payment: kotlin.Double,
    val isMarginCall: kotlin.Boolean,
    /* ISO8601 */
    val date: java.time.LocalDateTime
,
    val trades: kotlin.Array<OperationTrade>? = null,
    val commission: MoneyAmount? = null,
    val price: kotlin.Double? = null,
    /* Число инструментов в выставленной заявке */
    val quantity: kotlin.Int? = null,
    /* Число инструментов, исполненных в заявке */
    val quantityExecuted: kotlin.Int? = null,
    val figi: kotlin.String? = null,
    val instrumentType: InstrumentType? = null,
    val operationType: OperationTypeWithCommission? = null
) {
}