/**
 * OpenAPI
 * tinkoff.ru/invest OpenAPI.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: n.v.melnikov@tinkoff.ru
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models


/**
 * Статус заявки
 * Values: new,partiallyFill,fill,cancelled,replaced,pendingCancel,rejected,pendingReplace,pendingNew
 */
enum class OrderStatus(val value: kotlin.String){
    new("New"),// :/
    partiallyFill("PartiallyFill"),// :/
    fill("Fill"),// :/
    cancelled("Cancelled"),// :/
    replaced("Replaced"),// :/
    pendingCancel("PendingCancel"),// :/
    rejected("Rejected"),// :/
    pendingReplace("PendingReplace"),// :/
    pendingNew("PendingNew");// :/
}