/**
 * OpenAPI
 * tinkoff.ru/invest OpenAPI.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: n.v.melnikov@tinkoff.ru
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models

import io.swagger.client.models.OperationType
import io.swagger.client.models.OrderStatus
import io.swagger.client.models.OrderType

/**
 * 
 * @param orderId 
 * @param figi 
 * @param operation 
 * @param status 
 * @param requestedLots 
 * @param executedLots 
 * @param type 
 * @param price 
 */
data class Order (
    val orderId: kotlin.String,
    val figi: kotlin.String,
    val operation: OperationType,
    val status: OrderStatus,
    val requestedLots: kotlin.Int,
    val executedLots: kotlin.Int,
    val type: OrderType,
    val price: kotlin.Double

) {
}