/**
 * OpenAPI
 * tinkoff.ru/invest OpenAPI.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: n.v.melnikov@tinkoff.ru
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models

import io.swagger.client.models.InstrumentType
import io.swagger.client.models.MoneyAmount

/**
 * 
 * @param figi 
 * @param ticker 
 * @param isin 
 * @param instrumentType 
 * @param balance 
 * @param blocked 
 * @param expectedYield 
 * @param lots 
 * @param averagePositionPrice 
 * @param averagePositionPriceNoNkd 
 * @param name 
 */
data class PortfolioPosition (
    val figi: kotlin.String,
    val instrumentType: InstrumentType,
    val balance: kotlin.Double,
    val lots: kotlin.Int,
    val name: kotlin.String
,
    val ticker: kotlin.String? = null,
    val isin: kotlin.String? = null,
    val blocked: kotlin.Double? = null,
    val expectedYield: MoneyAmount? = null,
    val averagePositionPrice: MoneyAmount? = null,
    val averagePositionPriceNoNkd: MoneyAmount? = null
) {
}