/**
 * OpenAPI
 * tinkoff.ru/invest OpenAPI.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: n.v.melnikov@tinkoff.ru
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models


/**
 * 
 * Values: rUB,uSD,eUR,gBP,hKD,cHF,jPY,cNY,tRY
 */
enum class SandboxCurrency(val value: kotlin.String){
    rUB("RUB"),// :/
    uSD("USD"),// :/
    eUR("EUR"),// :/
    gBP("GBP"),// :/
    hKD("HKD"),// :/
    cHF("CHF"),// :/
    jPY("JPY"),// :/
    cNY("CNY"),// :/
    tRY("TRY");// :/
}