/**
 * OpenAPI
 * tinkoff.ru/invest OpenAPI.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: n.v.melnikov@tinkoff.ru
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models

import io.swagger.client.models.SandboxCurrency

/**
 * 
 * @param currency 
 * @param balance 
 */
data class SandboxSetCurrencyBalanceRequest (
    val currency: SandboxCurrency,
    val balance: kotlin.Double

) {
}