/**
 * OpenAPI
 * tinkoff.ru/invest OpenAPI.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: n.v.melnikov@tinkoff.ru
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.apis

import io.swagger.client.infrastructure.*
import io.swagger.client.models.OperationsResponse

class OperationsApi(basePath: kotlin.String = "https://api-invest.tinkoff.ru/openapi/") : ApiClient(basePath) {

    /**
     * Получение списка операций
     *
     * @param from Начало временного промежутка
     * @param to Конец временного промежутка
     * @param figi Figi инструмента для фильтрации (optional)
     * @param brokerAccountId Номер счета (по умолчанию - Тинькофф) (optional)
     * @return OperationsResponse
     */
    @Suppress("UNCHECKED_CAST")
    fun operationsGet(
        from: java.time.LocalDateTime,
        to: java.time.LocalDateTime,
        figi: kotlin.String? = null,
        brokerAccountId: kotlin.String? = null
    ): OperationsResponse {
        val localVariableQuery: MultiValueMap = mapOf(
            "from" to listOf("$from"),
            "to" to listOf("$to"),
            "figi" to listOf("$figi"),
            "brokerAccountId" to listOf("$brokerAccountId")
        )
        val localVariableConfig = RequestConfig(
            RequestMethod.GET,
            "/operations", query = localVariableQuery
        )
        val response = request<OperationsResponse>(
            localVariableConfig
        )

        return when (response.responseType) {
            ResponseType.Success -> (response as Success<*>).data as OperationsResponse
            ResponseType.Informational -> TODO()
            ResponseType.Redirection -> TODO()
            ResponseType.ClientError -> throw ClientException(
                (response as ClientError<*>).body as? String ?: "Client error"
            )
            ResponseType.ServerError -> throw ServerException((response as ServerError<*>).message ?: "Server error")
        }
    }
}
